version: '3'
services:
    nginx_forunit:
        build: "nginx_forunit"
        image: "nginx_forunit"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - "unitpy_api"
        environment:
            TZ: Asia/Tokyo
        volumes:
             - ./nginx_forunit/contents/:/usr/share/nginx/html/

    # APIServer_unitpy_api
    unitpy_api:
        build: "unitpy_api"
        image: "unitpy_api"
        restart: "no"
        expose:
            - "8300"
        environment:
            TZ: Asia/Tokyo
            PYTHONUNBUFFERED: "no"
        volumes:
             - ./unitpy_api/contents/:/www/ShoppingList/

    unit_mariadb:
        build: unit_mariadb
        image: unit_mariadb
        ports:
            - "33306:3306"
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: unit
            MYSQL_DATABASE: unit
            TZ: Asia/Tokyo
            # MYSQL_USER: unit
            # MYSQL_PASSWORD: unit