openapi: 3.0.0
info:
  title: ShoppingList API
  description: '買い物リストのサンプルAPI'
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1/shoppinglist_api/'
#contact:
 # name: API support
 # email: api@sample.com
# license:
  # name: MIT License
  # url: http://ja.wikipedia.org/wiki/MIT_License/
paths:
  /showList:
    get:
      summary: '買い物リスト一覧'
      description: '買い物リストの一覧を取得するAPI'
      parameters:
      - name: 'flag'
        in: 'query'   # パラメータの種類{query, header, path, formData, body}
        description: '完了フラッグ'
        required: false  # 必須or任意
        schema:
          type: integer  #　型
          format: int64  # フォーマット
      responses:      # レスポンス
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  #$ref: '#/components/List' # 参照するモデル
                example: # サンプルデータ
                  - id: 1
                    itemName: 'やぎ'
components:
  schemas: # スキーマオブジェクトの定義
    List: # モデル名
      type: object
      properties:
        id:
          type: integer
          format: int64
        itemName:
          type: string
