openapi: 3.0.0
info:
  title: ShoppingList API
  description: "買い物リストのサンプルAPI"
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1/shoppinglist_api/'
  # contact:
  #  email: api@sample.com
  license:
    name: MIT License
    url: http://ja.wikipedia.org/wiki/MIT_License/
paths:
  /showList:
    get:
      summary: "買い物リスト一覧"
      description: "買い物リストの一覧を取得するAPI"
      parameters:
        - name: "flag"
          in: "query"   # パラメータの種類{query, header, path, formData, body}
          description: "完了の有無"
          required: false  # 必須or任意
          schema:
            type: "integer"  #　型
            format: "int64"  # フォーマット
      # レスポンス
      responses:
        200:
          description: "成功"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "doggie"
# https://qiita.com/rllllho/items/53a0023b32f4c0f8eabb